import fs from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..", "..");
const catalog = JSON.parse(await fs.readFile(path.join(root, "assets", "data", "laser-sources.json"), "utf8"));
const header = (await fs.readFile(path.join(root, "_partials", "header.html"), "utf8")).trim();
const footer = (await fs.readFile(path.join(root, "_partials", "footer.html"), "utf8")).trim();
const routeRoot = "/technologies/laser-sources/";

const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char]);
const fullUrl = (route) => `https://wavlonlasers.com${route}`;
const fullImage = (image) => `https://wavlonlasers.com${image}`;
const getModel = (id) => catalog.models.find((model) => model.id === id);
const maxModels = catalog.models.filter((model) => model.brandId === "max-photonics").sort((a, b) => a.nominalPowerW - b.nominalPowerW || a.displayName.localeCompare(b.displayName));
const ipgModels = catalog.models.filter((model) => model.brandId === "ipg-photonics").sort((a, b) => a.nominalPowerW - b.nominalPowerW || a.displayName.localeCompare(b.displayName));
const maxHero = getModel("max-elite-mfsc-12000");
const ipgHero = getModel("ipg-yls-u-eco-10000");

function breadcrumbSchema(items) {
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: fullUrl(item.href) })),
  });
}

function breadcrumbs(items) {
  return `<div class="source-breadcrumbs"><div class="source-shell"><nav aria-label="Breadcrumb"><ol>${items.map((item, index) => `<li>${index === items.length - 1 ? esc(item.name) : `<a href="${item.href}">${esc(item.name)}</a>`}</li>`).join("")}</ol></nav></div></div>`;
}

function pageShell({ title, description, route, image, crumbs, body, script = "" }) {
  return `<!doctype html>
<html lang="en"><head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${esc(title)}</title><meta name="description" content="${esc(description)}">
  <link rel="canonical" href="${fullUrl(route)}">
  <meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${fullUrl(route)}"><meta property="og:image" content="${fullImage(image)}">
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/shared.css"><link rel="stylesheet" href="/assets/laser-sources.css">
  <script type="application/ld+json">${breadcrumbSchema(crumbs)}</script>
</head><body>
<!-- HEADER — inline copy -->
${header}
<main class="source-page">${breadcrumbs(crumbs)}${body}</main>
<!-- FOOTER — inline copy -->
${footer}
<script src="/nav.js" defer></script>${script}
</body></html>\n`;
}

function actions(primaryHref = "/contact/#quote", secondaryHref = `${routeRoot}compare/`, secondaryLabel = "Compare sources") {
  return `<div class="source-actions"><a class="source-btn source-btn--primary" href="${primaryHref}">Configure a machine →</a><a class="source-btn source-btn--ghost" href="${secondaryHref}">${secondaryLabel} →</a></div>`;
}

function modelCard(model, detail = false) {
  const href = detail ? `${routeRoot}max-photonics/elite-series/${model.slug}/` : `${routeRoot}compare/?models=${model.id}`;
  return `<article class="source-model-card" data-model-card data-search="${esc(`${model.displayName} ${model.series} ${model.nominalPowerLabel}`.toLowerCase())}"><div class="source-model-image"><img src="${model.primaryImage}" alt="${esc(model.displayName)} laser source" loading="lazy"></div><div class="source-model-copy"><div class="source-model-meta"><span>${esc(model.series)}</span><span>${esc(model.nominalPowerLabel)}</span></div><h3>${esc(model.displayName)}</h3><p>${esc(model.moduleType)} · ${esc(model.cooling)}. ${esc(model.powerStability)} published power stability.</p><div class="source-model-specs"><span>${esc(model.wavelength)}</span><span>${esc(model.powerRangeMatch ? "Wavlon range match" : "Engineering review")}</span></div><a class="source-link" href="${href}">${detail ? "View model details" : "Add to comparison"} →</a></div></article>`;
}

function serviceSection() {
  return `<section class="source-section source-section--dark"><div class="source-shell"><div class="source-service"><div class="source-service-logo"><img src="/assets/laser-sources/rise-tek/rise-tek-logo.webp" alt="Rise Tek Machinery"></div><div class="source-service-copy"><p class="source-kicker">Canadian service capability</p><h2>MAX Photonics Service Center at Rise Tek Machinery</h2><p>Local Wavlon and Rise Tek coordination gives Canadian and U.S. customers a clearer path for source selection, commissioning support and service escalation. Scope and response commitments are confirmed with each configured system.</p><ul class="source-service-points"><li>US / Canada local service</li><li>Configuration support</li><li>Commissioning coordination</li><li>Warranty escalation path</li></ul></div></div></div></section>`;
}

const hubCrumbs = [{ name: "Home", href: "/" }, { name: "Technologies", href: "/technologies/" }, { name: "Laser Sources", href: routeRoot }];
const hubBody = `<section class="source-hero"><div class="source-shell source-hero-grid"><div><p class="source-eyebrow">Machine configuration technology</p><h1 class="source-title">Choose the source behind the <span>cut.</span></h1><p class="source-lede">Explore verified MAX Photonics Elite Series and IPG Photonics CW fiber laser options, then compare the specifications that shape machine performance, integration and support.</p>${actions()}</div><div class="source-hero-card"><img src="${maxHero.primaryImage}" alt="MAX Photonics Elite Series laser source"><div class="source-hero-logos"><div style="display:flex;gap:20px;align-items:center"><img src="/assets/laser-sources/max/max-logo.svg" alt="MAX Photonics"><img src="/assets/laser-sources/ipg/ipg-logo.svg" alt="IPG Photonics"></div><div class="source-hero-stat"><span>Catalogued range</span><strong>0.1–120 kW</strong></div></div></div></div></section>
<div class="source-strip"><div class="source-shell source-strip-grid"><div class="source-strip-item"><strong>2</strong><span>Approved source brands</span></div><div class="source-strip-item"><strong>5</strong><span>Industrial CW series</span></div><div class="source-strip-item"><strong>40</strong><span>Model / power variants</span></div><div class="source-strip-item"><strong>21</strong><span>Current range matches</span></div></div></div>
<section class="source-section"><div class="source-shell"><div class="source-section-head"><div><p class="source-kicker">Source portfolio</p><h2 class="source-h2">Two proven paths to the right configuration.</h2></div><p class="source-intro">Start with the product families, then use Wavlon’s comparison tool to evaluate power, cooling, controls, efficiency, safety wording and warranty on the exact source under consideration.</p></div><div class="source-brand-grid"><a class="source-brand-card" href="${routeRoot}max-photonics/"><div class="source-brand-copy"><img class="source-brand-logo" src="/assets/laser-sources/max/max-logo.svg" alt="MAX Photonics"><h3>Elite Series</h3><p>Compact single-module and high-power multi-module sources from 500 W through 85 kW.</p><span class="source-link">Explore MAX Elite →</span></div><div class="source-brand-media"><img src="${maxHero.primaryImage}" alt="MAX Photonics Elite Series source"></div></a><a class="source-brand-card" href="${routeRoot}ipg-photonics/"><div class="source-brand-copy"><img class="source-brand-logo" src="/assets/laser-sources/ipg/ipg-logo.svg" alt="IPG Photonics"><h3>Industrial CW</h3><p>YLR, YLS and ECO architectures spanning precision racks, high-power cabinets and high-efficiency platforms.</p><span class="source-link">Explore IPG Photonics →</span></div><div class="source-brand-media"><img src="${ipgHero.primaryImage}" alt="IPG Photonics YLS-U-ECO source"></div></a></div></div></section>
<section class="source-section source-section--soft"><div class="source-shell"><div class="source-section-head"><div><p class="source-kicker">Selection framework</p><h2 class="source-h2">Compare what changes the machine.</h2></div><p class="source-intro">Kilowatts matter, but so do stability, beam delivery, communications, cooling, electrical efficiency and the exact certification package delivered with the configured machine.</p></div><div class="source-feature-grid"><div class="source-feature"><span class="source-feature-num">01 / POWER</span><h3>Process window</h3><p>Match output to the material, thickness, geometry, speed and edge-quality target—not a headline number alone.</p></div><div class="source-feature"><span class="source-feature-num">02 / OPTICS</span><h3>Beam delivery</h3><p>Review beam parameter product, fiber core and connector requirements with the selected cutting head.</p></div><div class="source-feature"><span class="source-feature-num">03 / CONTROLS</span><h3>Machine integration</h3><p>Confirm I/O, fieldbus, modulation and interlock behavior for the controller and automation package.</p></div><div class="source-feature"><span class="source-feature-num">04 / THERMAL</span><h3>Cooling load</h3><p>Size cooling and utilities for the exact source, ambient conditions and expected duty cycle.</p></div><div class="source-feature"><span class="source-feature-num">05 / COMPLIANCE</span><h3>Delivered approvals</h3><p>Use exact model and configuration documentation. Certification language is not uniform across every source.</p></div><div class="source-feature"><span class="source-feature-num">06 / SUPPORT</span><h3>Lifecycle coverage</h3><p>Review warranty, local service path, spare strategy and escalation support before purchase.</p></div></div><div class="source-warning"><div class="source-warning-icon">!</div><div><strong>Compatibility is configuration-specific.</strong>A power-range match in this catalog is an initial screening result. Wavlon engineering must validate the source, machine, head, controls, chiller and regional compliance package together.</div></div></div></section>
${serviceSection()}
<section class="source-section"><div class="source-shell"><div class="source-cta"><div><h2>Build a defensible shortlist.</h2><p>Select up to four source models and compare the published specifications side by side.</p></div><a class="source-btn source-btn--primary" href="${routeRoot}compare/">Open comparison →</a></div></div></section>`;

await writePage(routeRoot, pageShell({ title: "Laser Sources | MAX Elite & IPG CW | Wavlon Lasers", description: "Compare MAX Photonics Elite Series and IPG Photonics CW fiber laser sources for Wavlon machine configurations, with model-level power, efficiency, controls, certifications and warranty details.", route: routeRoot, image: maxHero.primaryImage, crumbs: hubCrumbs, body: hubBody }));

function brandBody({ brand, models, hero, max }) {
  const min = Math.min(...models.map((model) => model.nominalPowerW));
  const maxPower = Math.max(...models.map((model) => model.nominalPowerW));
  const logoClass = max ? "source-brand-hero-logo source-brand-hero-logo--max" : "source-brand-hero-logo";
  const logo = max ? "/assets/laser-sources/max/max-logo.svg" : "/assets/laser-sources/ipg/ipg-logo.svg";
  const overview = max
    ? `<section class="source-section source-section--soft"><div class="source-shell"><div class="source-section-head"><div><p class="source-kicker">Elite Series highlights</p><h2 class="source-h2">Integration-first performance.</h2></div><p class="source-intro">MAX positions Elite Series around cost-performance balance, PL-d safety, multi-function I/O, plug-and-play deployment and redundancy. Exact certification and warranty wording is preserved per model below.</p></div><div class="source-feature-grid"><div class="source-feature"><span class="source-feature-num">SAFETY</span><h3>Performance Level D</h3><p>PL-d safety wording appears across the reviewed Elite Series product pages.</p></div><div class="source-feature"><span class="source-feature-num">CONTROLS</span><h3>Multi-function I/O</h3><p>Digital I/O is standard; EtherCAT and PROFINET options are published on reviewed models.</p></div><div class="source-feature"><span class="source-feature-num">UPTIME</span><h3>Power redundancy</h3><p>Reviewed product pages publish at least 5% power redundancy for operating resilience.</p></div><div class="source-feature"><span class="source-feature-num">DEPLOYMENT</span><h3>Plug and play</h3><p>Designed for straightforward system integration with configuration-specific validation.</p></div><div class="source-feature"><span class="source-feature-num">COVERAGE</span><h3>Model-level approvals</h3><p>CE and FDA across reviewed pages; ETL and UL-compatible wording appear on selected models.</p></div><div class="source-feature"><span class="source-feature-num">WARRANTY</span><h3>Up to five years</h3><p>Pages list two- or three-year standard coverage with optional extension up to five years.</p></div></div><div class="source-warning"><div class="source-warning-icon">!</div><div><strong>Certification language varies.</strong>Do not describe the entire Elite Series as UL-certified. Review each model’s exact CE, FDA, ETL and UL-compatible wording below and reconfirm the delivered configuration.</div></div></div></section>`
    : `<section class="source-section source-section--soft"><div class="source-shell"><div class="source-section-head"><div><p class="source-kicker">Industrial CW portfolio</p><h2 class="source-h2">Choose architecture as carefully as power.</h2></div><p class="source-intro">YLR racks serve lower-power and precision requirements, YLS cabinets scale into high-power processing, and ECO platforms target 50% wall-plug efficiency in compact or high-power formats.</p></div><div class="source-feature-grid"><div class="source-feature"><span class="source-feature-num">YLR</span><h3>Precision racks</h3><p>100 W to 4 kW representative variants with single-mode capability available through 3 kW.</p></div><div class="source-feature"><span class="source-feature-num">YLS</span><h3>High-power cabinets</h3><p>Representative 8–120 kW variants from the industrial high-power family.</p></div><div class="source-feature"><span class="source-feature-num">YLS-U-ECO</span><h3>Ultra-compact ECO</h3><p>4, 6 and 10 kW configurations with published 50% wall-plug efficiency.</p></div><div class="source-feature"><span class="source-feature-num">YLS-ECO</span><h3>High-power ECO</h3><p>20 and 30 kW representative configurations with published 50% efficiency.</p></div><div class="source-feature"><span class="source-feature-num">SAFETY</span><h3>Class 4 / IEC marking</h3><p>Official datasheets show Class 4 laser product and IEC 60825-1:2014 marking.</p></div><div class="source-feature"><span class="source-feature-num">VALIDATION</span><h3>Configuration review</h3><p>Options, interfaces, connector, cooling and approvals depend on the selected configuration.</p></div></div></div></section>`;
  return `<section class="source-hero"><div class="source-shell source-hero-grid"><div><img class="${logoClass}" src="${logo}" alt="${esc(brand)}"><p class="source-eyebrow">Fiber laser source portfolio</p><h1 class="source-title">${max ? "Elite Series" : "Industrial CW"} <span>sources.</span></h1><p class="source-lede">${max ? "From compact 500 W racks to 85 kW multi-module platforms, with model-level integration, safety and coverage details." : "YLR, YLS and ECO platforms spanning 100 W precision racks through representative 120 kW high-power configurations."}</p>${actions()}</div><div class="source-hero-card"><img src="${hero.primaryImage}" alt="${esc(hero.displayName)}"><div class="source-hero-logos"><img src="${logo}" alt="${esc(brand)}"><div class="source-hero-stat"><span>Reviewed variants</span><strong>${models.length}</strong></div></div></div></div></section><div class="source-strip"><div class="source-shell source-strip-grid"><div class="source-strip-item"><strong>${models.length}</strong><span>Catalogued variants</span></div><div class="source-strip-item"><strong>${min < 1000 ? `${min} W` : `${min / 1000} kW`}</strong><span>Lowest reviewed power</span></div><div class="source-strip-item"><strong>${maxPower / 1000} kW</strong><span>Highest reviewed power</span></div><div class="source-strip-item"><strong>${new Set(models.map((model) => model.series)).size}</strong><span>Product series</span></div></div></div>${overview}${max ? serviceSection() : ""}<section class="source-section"><div class="source-shell"><div class="source-section-head"><div><p class="source-kicker">Reviewed catalog</p><h2 class="source-h2">${max ? "Every Elite Series product." : "Representative power variants."}</h2></div><p class="source-intro">Use these published specifications to build a shortlist, then complete Wavlon engineering review before a source is included in a machine quotation.</p></div><div class="source-model-grid">${models.map((model) => modelCard(model, max)).join("")}</div><p class="source-fineprint">Specifications and commercial terms are manufacturer reference data retrieved 2026-08-20 and may change. Final availability, approvals and warranty are configuration- and region-dependent.</p></div></section><section class="source-section source-section--soft"><div class="source-shell"><div class="source-cta"><div><h2>Compare exact models.</h2><p>Put up to four MAX and IPG variants side by side, including certification and compatibility notes.</p></div><a class="source-btn source-btn--primary" href="${routeRoot}compare/">Open comparison →</a></div></div></section>`;
}

const maxRoute = `${routeRoot}max-photonics/`;
const maxCrumbs = [...hubCrumbs, { name: "MAX Photonics", href: maxRoute }];
await writePage(maxRoute, pageShell({ title: "MAX Photonics Elite Series | Wavlon Lasers", description: "Explore all reviewed MAX Photonics Elite Series fiber laser sources from 500 W to 85 kW, including model-level power, controls, certifications, warranty and Wavlon compatibility screening.", route: maxRoute, image: maxHero.primaryImage, crumbs: maxCrumbs, body: brandBody({ brand: "MAX Photonics", models: maxModels, hero: maxHero, max: true }) }));

const ipgRoute = `${routeRoot}ipg-photonics/`;
const ipgCrumbs = [...hubCrumbs, { name: "IPG Photonics", href: ipgRoute }];
await writePage(ipgRoute, pageShell({ title: "IPG Photonics CW Fiber Lasers | Wavlon Lasers", description: "Explore IPG Photonics YLR, YLS, YLS-U-ECO and YLS-ECO industrial CW fiber laser options with representative power, efficiency, cooling and integration specifications.", route: ipgRoute, image: ipgHero.primaryImage, crumbs: ipgCrumbs, body: brandBody({ brand: "IPG Photonics", models: ipgModels, hero: ipgHero, max: false }) }));

const compareRoute = `${routeRoot}compare/`;
const compareCrumbs = [...hubCrumbs, { name: "Compare", href: compareRoute }];
const compareBody = `<section class="source-hero" style="padding:75px 0 62px"><div class="source-shell"><p class="source-eyebrow">Manual source comparison</p><h1 class="source-title">Compare the details that <span>change the machine.</span></h1><p class="source-lede">Select up to four MAX Elite or IPG CW source variants. Identical rows can be hidden so the meaningful differences stay visible.</p></div></section><section class="source-section source-section--soft"><div class="source-shell"><div class="source-compare-layout" data-laser-source-compare><aside class="source-picker"><h2>Choose sources</h2><p>Mix brands and power levels. Selection is saved in the page URL for sharing.</p><label class="source-field"><span style="font-size:10px;font-weight:850;letter-spacing:.14em;text-transform:uppercase;color:#657180">Search catalog</span><input class="source-picker-search" type="search" data-picker-search placeholder="Model, series or power"></label><div data-picker-options></div><div class="source-picker-status" data-picker-status aria-live="polite">Loading catalog…</div></aside><div class="source-compare-panel"><div class="source-compare-actions"><label><input type="checkbox" data-differences-only> Show differences only</label><button class="source-clear" type="button" data-clear-compare>Clear selections</button></div><div data-compare-table><div class="source-empty">Loading comparison catalog…</div></div><p class="source-fineprint">Comparison values reproduce manufacturer-published reference data retrieved 2026-08-20. “Wavlon range match” is screening only; final engineering, delivered approvals and commercial terms must be validated before quotation.</p></div></div></div></section><section class="source-section"><div class="source-shell"><div class="source-cta"><div><h2>Need a configured recommendation?</h2><p>Share your material, thickness, part mix, production target and utilities with Wavlon engineering.</p></div><a class="source-btn source-btn--primary" href="/contact/#quote">Request a configuration →</a></div></div></section>`;
await writePage(compareRoute, pageShell({ title: "Compare Fiber Laser Sources | Wavlon Lasers", description: "Manually compare up to four MAX Photonics Elite Series and IPG Photonics CW fiber laser source models by power, efficiency, cooling, controls, certifications, warranty and compatibility.", route: compareRoute, image: maxHero.primaryImage, crumbs: compareCrumbs, body: compareBody, script: '<script src="/assets/laser-source-compare.js" defer></script>' }));

for (const model of maxModels) {
  const route = `${routeRoot}max-photonics/elite-series/${model.slug}/`;
  const crumbs = [...maxCrumbs, { name: model.displayName, href: route }];
  const specs = [
    ["Nominal power", model.nominalPowerLabel], ["Architecture", `${model.moduleType} · ${model.housingForm}`],
    ["Wavelength", model.wavelength], ["Power tunability", model.powerTunability], ["Power stability", model.powerStability],
    ["Power redundancy", model.powerRedundancy], ["Modulation", model.modulationFrequency], ["Beam quality", model.beamQuality],
    ["Fiber / connector", model.fiberConnectors], ["Interface", model.interface], ["Cooling", model.cooling],
    ["Certifications / safety", model.certifications], ["Warranty", model.warranty], ["Efficiency", model.efficiency],
  ];
  const body = `<section class="source-hero" style="padding:78px 0 70px"><div class="source-shell source-hero-grid"><div><img class="source-brand-hero-logo source-brand-hero-logo--max" src="/assets/laser-sources/max/max-logo.svg" alt="MAX Photonics"><p class="source-eyebrow">Elite Series · ${esc(model.nominalPowerLabel)}</p><h1 class="source-title">${esc(model.displayName)}.</h1><p class="source-lede">${esc(model.description)}</p>${actions("/contact/#quote", `${compareRoute}?models=${model.id}`, "Compare this model")}</div><div class="source-detail-image"><img src="${model.primaryImage}" alt="${esc(model.displayName)} fiber laser source"></div></div></section><section class="source-section"><div class="source-shell source-detail-grid"><div><p class="source-kicker">Published specification</p><h2 class="source-h2">Integration profile.</h2><p class="source-intro" style="margin-top:18px">${esc(model.compatibilityNote)}</p><div class="source-warning"><div class="source-warning-icon">!</div><div><strong>Engineering validation required.</strong>Power is only one selection input. Confirm machine, head, fiber, chiller, controls, utilities and delivered regional compliance together.</div></div></div><dl class="source-spec-grid">${specs.map(([label, value]) => `<div class="source-spec"><dt>${esc(label)}</dt><dd>${esc(value || "Confirm by configuration")}</dd></div>`).join("")}</dl></div></section><section class="source-section source-section--soft"><div class="source-shell"><div class="source-section-head"><div><p class="source-kicker">Official references</p><h2 class="source-h2">Source trail.</h2></div><p class="source-intro">The catalog preserves the product page and original manufacturer image location for repeatable review.</p></div><ul class="source-source-list">${model.sourceUrls.map((url) => `<li><a href="${esc(url)}" rel="noopener" target="_blank">${esc(url)}</a></li>`).join("")}<li><a href="${esc(model.sourceImageUrl)}" rel="noopener" target="_blank">Official image origin: ${esc(model.sourceImageUrl)}</a></li></ul><p class="source-fineprint">Retrieved ${esc(model.retrievedAt)}. Specifications, certifications, availability and warranty are subject to manufacturer revision and selected configuration.</p></div></section>${serviceSection()}<section class="source-section"><div class="source-shell"><div class="source-cta"><div><h2>Configure ${esc(model.displayName)}.</h2><p>Wavlon will validate the complete source, machine and application package before quotation.</p></div><a class="source-btn source-btn--primary" href="/contact/#quote">Start configuration →</a></div></div></section>`;
  await writePage(route, pageShell({ title: `${model.displayName} MAX Elite | Wavlon Lasers`, description: `${model.displayName} MAX Photonics Elite Series fiber laser source specifications, controls, cooling, certifications, warranty and Wavlon compatibility screening.`, route, image: model.primaryImage, crumbs, body }));
}

async function writePage(route, html) {
  const relative = route.replace(/^\//, "");
  const dir = path.join(root, relative);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, "index.html"), html);
}

console.log(JSON.stringify({ hub: 1, brandPages: 2, comparePages: 1, maxDetailPages: maxModels.length }));
