-- Laser-source knowledge base for Wavlon Lasers.
-- Official-source snapshot generated 2026-08-20T17:42:39.032Z.

create table if not exists public.laser_source_brands (
  id text primary key,
  name text not null,
  official_name text not null,
  website_url text not null,
  logo_path text,
  summary text,
  source_retrieved_at date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.laser_source_series (
  id text primary key,
  brand_id text not null references public.laser_source_brands(id) on delete cascade,
  name text not null,
  min_power_w integer not null check (min_power_w > 0),
  max_power_w integer not null check (max_power_w >= min_power_w),
  source_urls jsonb not null default '[]'::jsonb check (jsonb_typeof(source_urls) = 'array'),
  source_retrieved_at date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.laser_source_models (
  id text primary key,
  brand_id text not null references public.laser_source_brands(id) on delete cascade,
  series_id text not null references public.laser_source_series(id) on delete cascade,
  model text not null,
  display_name text not null,
  slug text not null unique,
  product_type text not null,
  nominal_power_w integer not null check (nominal_power_w > 0),
  nominal_power_label text not null,
  module_type text,
  housing_form text,
  polarization text,
  wavelength text,
  power_tunability text,
  power_stability text,
  power_redundancy text,
  modulation_frequency text,
  beam_quality text,
  fiber_connectors text,
  interface text,
  cooling text,
  certifications text,
  warranty text,
  efficiency text,
  applications jsonb not null default '[]'::jsonb check (jsonb_typeof(applications) = 'array'),
  description text,
  power_range_match boolean not null default false,
  compatibility_note text,
  primary_image_path text,
  source_image_url text,
  source_urls jsonb not null default '[]'::jsonb check (jsonb_typeof(source_urls) = 'array'),
  source_retrieved_at date not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists laser_source_series_brand_idx on public.laser_source_series (brand_id);
create index if not exists laser_source_models_brand_idx on public.laser_source_models (brand_id);
create index if not exists laser_source_models_series_idx on public.laser_source_models (series_id);
create index if not exists laser_source_models_power_idx on public.laser_source_models (nominal_power_w);
create index if not exists laser_source_models_published_idx on public.laser_source_models (published) where published = true;

alter table public.laser_source_brands enable row level security;
alter table public.laser_source_series enable row level security;
alter table public.laser_source_models enable row level security;

drop policy if exists "Public can read laser source brands" on public.laser_source_brands;
create policy "Public can read laser source brands"
  on public.laser_source_brands for select to anon, authenticated using (true);

drop policy if exists "Public can read laser source series" on public.laser_source_series;
create policy "Public can read laser source series"
  on public.laser_source_series for select to anon, authenticated using (true);

drop policy if exists "Public can read published laser source models" on public.laser_source_models;
create policy "Public can read published laser source models"
  on public.laser_source_models for select to anon, authenticated using (published = true);

revoke all on table public.laser_source_brands from anon, authenticated;
revoke all on table public.laser_source_series from anon, authenticated;
revoke all on table public.laser_source_models from anon, authenticated;
grant select on table public.laser_source_brands to anon, authenticated;
grant select on table public.laser_source_series to anon, authenticated;
grant select on table public.laser_source_models to anon, authenticated;

insert into public.laser_source_brands
  (id, name, official_name, website_url, logo_path, summary, source_retrieved_at)
values
('max-photonics', 'MAX Photonics', 'Maxphotonics', 'https://maxlasers.com/', '/assets/laser-sources/max/max-logo.svg', 'Elite Series CW fiber lasers from compact single-module sources through high-power multi-module cabinets.', '2026-08-20'),
('ipg-photonics', 'IPG Photonics', 'IPG Photonics Corporation', 'https://www.ipgphotonics.com/', '/assets/laser-sources/ipg/ipg-logo.svg', 'Industrial CW fiber laser racks, high-power cabinets and high-efficiency ECO configurations.', '2026-08-20')
on conflict (id) do update set
  name = excluded.name,
  official_name = excluded.official_name,
  website_url = excluded.website_url,
  logo_path = excluded.logo_path,
  summary = excluded.summary,
  source_retrieved_at = excluded.source_retrieved_at,
  updated_at = now();

insert into public.laser_source_series
  (id, brand_id, name, min_power_w, max_power_w, source_urls, source_retrieved_at)
values
('max-elite', 'max-photonics', 'Elite Series', 500, 85000, '["https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20'),
('ipg-ylr', 'ipg-photonics', 'YLR Series', 100, 4000, '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20'),
('ipg-yls', 'ipg-photonics', 'YLS Series', 8000, 120000, '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/5b6f3db3-e2af-4331-b634-b0c000f9351e/IPG_YLS-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20'),
('ipg-yls-u-eco', 'ipg-photonics', 'YLS-U-ECO Series', 4000, 10000, '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-efficiency-fiber-lasers","https://cdn.ipgphotonics.com/4be8a158-00db-4fa5-ae1a-b01f00ee3212/IPG_YLS-U-ECO_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20'),
('ipg-yls-eco', 'ipg-photonics', 'YLS-ECO Series', 20000, 30000, '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-efficiency-fiber-lasers","https://cdn.ipgphotonics.com/607abf5d-cb13-458e-8b1f-b0b40131917f/IPG_YLS-ECO-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20')
on conflict (id) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  min_power_w = excluded.min_power_w,
  max_power_w = excluded.max_power_w,
  source_urls = excluded.source_urls,
  source_retrieved_at = excluded.source_retrieved_at,
  updated_at = now();

insert into public.laser_source_models
  (id, brand_id, series_id, model, display_name, slug, product_type, nominal_power_w,
   nominal_power_label, module_type, housing_form, polarization, wavelength, power_tunability,
   power_stability, power_redundancy, modulation_frequency, beam_quality, fiber_connectors,
   interface, cooling, certifications, warranty, efficiency, applications, description,
   power_range_match, compatibility_note, primary_image_path, source_image_url, source_urls,
   source_retrieved_at, published)
values
('ipg-ylr-100', 'ipg-photonics', 'ipg-ylr', 'YLR-100', 'YLR 100 W', 'ipg-ylr-100', 'CW / Modulated fiber laser', 100, '100 W', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'Affixed collimator available', 'Analogue, RS-232 or Ethernet; options vary', 'Air or water, depending on model', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 100 W nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-150', 'ipg-photonics', 'ipg-ylr', 'YLR-150', 'YLR 150 W', 'ipg-ylr-150', 'CW / Modulated fiber laser', 150, '150 W', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'Affixed collimator available', 'Analogue, RS-232 or Ethernet; options vary', 'Air or water, depending on model', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 150 W nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-200', 'ipg-photonics', 'ipg-ylr', 'YLR-200', 'YLR 200 W', 'ipg-ylr-200', 'CW / Modulated fiber laser', 200, '200 W', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'Affixed collimator available', 'Analogue, RS-232 or Ethernet; options vary', 'Air or water, depending on model', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 200 W nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-300', 'ipg-photonics', 'ipg-ylr', 'YLR-300', 'YLR 300 W', 'ipg-ylr-300', 'CW / Modulated fiber laser', 300, '300 W', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'Affixed collimator available', 'Analogue, RS-232 or Ethernet; options vary', 'Air or water, depending on model', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 300 W nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-400', 'ipg-photonics', 'ipg-ylr', 'YLR-400', 'YLR 400 W', 'ipg-ylr-400', 'CW / Modulated fiber laser', 400, '400 W', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'Affixed collimator available', 'Analogue, RS-232 or Ethernet; options vary', 'Air or water, depending on model', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 400 W nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-500', 'ipg-photonics', 'ipg-ylr', 'YLR-500', 'YLR 500 W', 'ipg-ylr-500', 'CW / Modulated fiber laser', 500, '500 W', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'HLC-8 / QBH-type', 'Analogue, RS-232 or Ethernet; options vary', 'Air or water, depending on model', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 500 W nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-600', 'ipg-photonics', 'ipg-ylr', 'YLR-600', 'YLR 600 W', 'ipg-ylr-600', 'CW / Modulated fiber laser', 600, '600 W', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'HLC-8 / QBH-type', 'Analogue, RS-232 or Ethernet; options vary', 'Air or water, depending on model', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 600 W nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-700', 'ipg-photonics', 'ipg-ylr', 'YLR-700', 'YLR 700 W', 'ipg-ylr-700', 'CW / Modulated fiber laser', 700, '700 W', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'HLC-8 / QBH-type', 'Analogue, RS-232 or Ethernet; options vary', 'Air or water, depending on model', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 700 W nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-1000', 'ipg-photonics', 'ipg-ylr', 'YLR-1000', 'YLR 1 kW', 'ipg-ylr-1000', 'CW / Modulated fiber laser', 1000, '1 kW', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'HLC-8 / QBH-type', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 1 kW nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-1500', 'ipg-photonics', 'ipg-ylr', 'YLR-1500', 'YLR 1.5 kW', 'ipg-ylr-1500', 'CW / Modulated fiber laser', 1500, '1.5 kW', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'HLC-8 / QBH-type', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 1.5 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-2000', 'ipg-photonics', 'ipg-ylr', 'YLR-2000', 'YLR 2 kW', 'ipg-ylr-2000', 'CW / Modulated fiber laser', 2000, '2 kW', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'HLC-8 / QBH-type', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 2 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-2500', 'ipg-photonics', 'ipg-ylr', 'YLR-2500', 'YLR 2.5 kW', 'ipg-ylr-2500', 'CW / Modulated fiber laser', 2500, '2.5 kW', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'HLC-8 / QBH-type', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 2.5 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-3000', 'ipg-photonics', 'ipg-ylr', 'YLR-3000', 'YLR 3 kW', 'ipg-ylr-3000', 'CW / Modulated fiber laser', 3000, '3 kW', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Single-mode M² <1.1 available; multimode options also available', 'HLC-8 / QBH-type', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 3 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-ylr-4000', 'ipg-photonics', 'ipg-ylr', 'YLR-4000', 'YLR 4 kW', 'ipg-ylr-4000', 'CW / Modulated fiber laser', 4000, '4 kW', 'Single-module rack', '19-inch rack', 'Random / configuration-dependent', '1070 ±10 nm', '10–100%', '±0.5%', 'Not published for this series', '0–50 kHz', 'Multimode; fiber-dependent', 'HLC-8 / QBH-type', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', 'High wall-plug efficiency; exact value not stated in current datasheet', '["Precision cutting","Welding","Additive manufacturing","Heat treating"]'::jsonb, 'High-Power Fiber Laser Racks with 4 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/ylr-series.webp', 'https://cdn.ipgphotonics.com/1099a549-0ca4-42ba-a0b1-b01400e28df4/YLR_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/6f98cba1-ae50-4feb-8635-b10901309bcd/IPG_YLR-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-u-eco-4000', 'ipg-photonics', 'ipg-yls-u-eco', 'YLS-U-ECO-4000', 'YLS-U-ECO 4 kW', 'ipg-yls-u-eco-4000', 'CW / Modulated high-efficiency fiber laser', 4000, '4 kW', 'Ultra-compact cabinet', 'Compact cabinet', 'Random / configuration-dependent', '1074 ±6 nm', '10–100%', '±2%', 'Not published for this series', '0–5 kHz', 'BPP 2.0–6.0 mm·mrad, fiber-dependent', 'Confirm by configuration', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '50%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'Ultra-Compact High-Efficiency Lasers with 4 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/yls-u-eco-series.webp', 'https://cdn.ipgphotonics.com/6275d977-3d6e-423d-85bb-b01401337478/YLS_ECO_Series_Main_cms_hero_1x.png?disable=upscale&width=834&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-efficiency-fiber-lasers","https://cdn.ipgphotonics.com/4be8a158-00db-4fa5-ae1a-b01f00ee3212/IPG_YLS-U-ECO_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-u-eco-6000', 'ipg-photonics', 'ipg-yls-u-eco', 'YLS-U-ECO-6000', 'YLS-U-ECO 6 kW', 'ipg-yls-u-eco-6000', 'CW / Modulated high-efficiency fiber laser', 6000, '6 kW', 'Ultra-compact cabinet', 'Compact cabinet', 'Random / configuration-dependent', '1074 ±6 nm', '10–100%', '±2%', 'Not published for this series', '0–5 kHz', 'BPP 2.0–6.0 mm·mrad, fiber-dependent', 'Confirm by configuration', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '50%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'Ultra-Compact High-Efficiency Lasers with 6 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/yls-u-eco-series.webp', 'https://cdn.ipgphotonics.com/6275d977-3d6e-423d-85bb-b01401337478/YLS_ECO_Series_Main_cms_hero_1x.png?disable=upscale&width=834&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-efficiency-fiber-lasers","https://cdn.ipgphotonics.com/4be8a158-00db-4fa5-ae1a-b01f00ee3212/IPG_YLS-U-ECO_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-8000', 'ipg-photonics', 'ipg-yls', 'YLS-8000', 'YLS 8 kW', 'ipg-yls-8000', 'CW / Modulated fiber laser', 8000, '8 kW', 'Multi-module cabinet', 'Sealed industrial cabinet', 'Random / configuration-dependent', '1070 ±5 nm', '10–100%', '±1%', 'Hot-diode redundancy; configuration-dependent', '0–5 kHz', 'Feed/process fiber dependent; see official datasheet', 'HLC (QBH-type) or LCA (QD-style)', 'Digital / analogue / LaserNet; industrial fieldbus options', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '>40%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'High-Power Laser Cabinets with 8 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/yls-series.webp', 'https://cdn.ipgphotonics.com/d486cdff-f45c-466f-8c8e-b01400e28e5d/YLS_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/5b6f3db3-e2af-4331-b634-b0c000f9351e/IPG_YLS-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-10000', 'ipg-photonics', 'ipg-yls', 'YLS-10000', 'YLS 10 kW', 'ipg-yls-10000', 'CW / Modulated fiber laser', 10000, '10 kW', 'Multi-module cabinet', 'Sealed industrial cabinet', 'Random / configuration-dependent', '1070 ±5 nm', '10–100%', '±1%', 'Hot-diode redundancy; configuration-dependent', '0–5 kHz', 'Feed/process fiber dependent; see official datasheet', 'HLC (QBH-type) or LCA (QD-style)', 'Digital / analogue / LaserNet; industrial fieldbus options', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '>40%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'High-Power Laser Cabinets with 10 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/yls-series.webp', 'https://cdn.ipgphotonics.com/d486cdff-f45c-466f-8c8e-b01400e28e5d/YLS_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/5b6f3db3-e2af-4331-b634-b0c000f9351e/IPG_YLS-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-u-eco-10000', 'ipg-photonics', 'ipg-yls-u-eco', 'YLS-U-ECO-10000', 'YLS-U-ECO 10 kW', 'ipg-yls-u-eco-10000', 'CW / Modulated high-efficiency fiber laser', 10000, '10 kW', 'Ultra-compact cabinet', 'Compact cabinet', 'Random / configuration-dependent', '1074 ±6 nm', '10–100%', '±2%', 'Not published for this series', '0–5 kHz', 'BPP 2.0–6.0 mm·mrad, fiber-dependent', 'Confirm by configuration', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '50%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'Ultra-Compact High-Efficiency Lasers with 10 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/yls-u-eco-series.webp', 'https://cdn.ipgphotonics.com/6275d977-3d6e-423d-85bb-b01401337478/YLS_ECO_Series_Main_cms_hero_1x.png?disable=upscale&width=834&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-efficiency-fiber-lasers","https://cdn.ipgphotonics.com/4be8a158-00db-4fa5-ae1a-b01f00ee3212/IPG_YLS-U-ECO_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-20000', 'ipg-photonics', 'ipg-yls', 'YLS-20000', 'YLS 20 kW', 'ipg-yls-20000', 'CW / Modulated fiber laser', 20000, '20 kW', 'Multi-module cabinet', 'Sealed industrial cabinet', 'Random / configuration-dependent', '1070 ±5 nm', '10–100%', '±1%', 'Hot-diode redundancy; configuration-dependent', '0–5 kHz', 'Feed/process fiber dependent; see official datasheet', 'HLC (QBH-type) or LCA (QD-style)', 'Digital / analogue / LaserNet; industrial fieldbus options', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '>40%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'High-Power Laser Cabinets with 20 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/yls-series.webp', 'https://cdn.ipgphotonics.com/d486cdff-f45c-466f-8c8e-b01400e28e5d/YLS_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/5b6f3db3-e2af-4331-b634-b0c000f9351e/IPG_YLS-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-eco-20000', 'ipg-photonics', 'ipg-yls-eco', 'YLS-ECO-20000', 'YLS-ECO 20 kW', 'ipg-yls-eco-20000', 'CW / Modulated high-efficiency fiber laser', 20000, '20 kW', 'High-power cabinet', 'Industrial cabinet', 'Random / configuration-dependent', '1074 ±6 nm', '10–100%', '±2%', 'Not published for this series', '0–5 kHz', 'BPP 3.9–6.5 mm·mrad, fiber-dependent', 'Confirm by configuration', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '50%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'High-Efficiency High-Power Lasers with 20 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/yls-eco-series.webp', 'https://cdn.ipgphotonics.com/6275d977-3d6e-423d-85bb-b01401337478/YLS_ECO_Series_Main_cms_hero_2x.png?disable=upscale&width=1668&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-efficiency-fiber-lasers","https://cdn.ipgphotonics.com/607abf5d-cb13-458e-8b1f-b0b40131917f/IPG_YLS-ECO-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-eco-30000', 'ipg-photonics', 'ipg-yls-eco', 'YLS-ECO-30000', 'YLS-ECO 30 kW', 'ipg-yls-eco-30000', 'CW / Modulated high-efficiency fiber laser', 30000, '30 kW', 'High-power cabinet', 'Industrial cabinet', 'Random / configuration-dependent', '1074 ±6 nm', '10–100%', '±2%', 'Not published for this series', '0–5 kHz', 'BPP 3.9–6.5 mm·mrad, fiber-dependent', 'Confirm by configuration', 'Analogue, RS-232 or Ethernet; options vary', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '50%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'High-Efficiency High-Power Lasers with 30 kW nominal output. Exact options and regional availability require configuration review.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/ipg/yls-eco-series.webp', 'https://cdn.ipgphotonics.com/6275d977-3d6e-423d-85bb-b01401337478/YLS_ECO_Series_Main_cms_hero_2x.png?disable=upscale&width=1668&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-efficiency-fiber-lasers","https://cdn.ipgphotonics.com/607abf5d-cb13-458e-8b1f-b0b40131917f/IPG_YLS-ECO-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-40000', 'ipg-photonics', 'ipg-yls', 'YLS-40000', 'YLS 40 kW', 'ipg-yls-40000', 'CW / Modulated fiber laser', 40000, '40 kW', 'Multi-module cabinet', 'Sealed industrial cabinet', 'Random / configuration-dependent', '1070 ±5 nm', '10–100%', '±1%', 'Hot-diode redundancy; configuration-dependent', '0–5 kHz', 'Feed/process fiber dependent; see official datasheet', 'HLC (QBH-type) or LCA (QD-style)', 'Digital / analogue / LaserNet; industrial fieldbus options', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '>40%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'High-Power Laser Cabinets with 40 kW nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/yls-series.webp', 'https://cdn.ipgphotonics.com/d486cdff-f45c-466f-8c8e-b01400e28e5d/YLS_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/5b6f3db3-e2af-4331-b634-b0c000f9351e/IPG_YLS-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-60000', 'ipg-photonics', 'ipg-yls', 'YLS-60000', 'YLS 60 kW', 'ipg-yls-60000', 'CW / Modulated fiber laser', 60000, '60 kW', 'Multi-module cabinet', 'Sealed industrial cabinet', 'Random / configuration-dependent', '1070 ±5 nm', '10–100%', '±1%', 'Hot-diode redundancy; configuration-dependent', '0–5 kHz', 'Feed/process fiber dependent; see official datasheet', 'HLC (QBH-type) or LCA (QD-style)', 'Digital / analogue / LaserNet; industrial fieldbus options', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '>40%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'High-Power Laser Cabinets with 60 kW nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/yls-series.webp', 'https://cdn.ipgphotonics.com/d486cdff-f45c-466f-8c8e-b01400e28e5d/YLS_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/5b6f3db3-e2af-4331-b634-b0c000f9351e/IPG_YLS-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('ipg-yls-120000', 'ipg-photonics', 'ipg-yls', 'YLS-120000', 'YLS 120 kW', 'ipg-yls-120000', 'CW / Modulated fiber laser', 120000, '120 kW', 'Multi-module cabinet', 'Sealed industrial cabinet', 'Random / configuration-dependent', '1070 ±5 nm', '10–100%', '±1%', 'Hot-diode redundancy; configuration-dependent', '0–5 kHz', 'Feed/process fiber dependent; see official datasheet', 'HLC (QBH-type) or LCA (QD-style)', 'Digital / analogue / LaserNet; industrial fieldbus options', 'Water-cooled', 'Class 4 laser product; IEC 60825-1:2014 marking shown in official datasheet', 'Confirm with Wavlon/IPG for selected configuration', '>40%', '["2D/3D cutting","Welding","Drilling","Cladding","Brazing","Heat treating"]'::jsonb, 'High-Power Laser Cabinets with 120 kW nominal output. Exact options and regional availability require configuration review.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/ipg/yls-series.webp', 'https://cdn.ipgphotonics.com/d486cdff-f45c-466f-8c8e-b01400e28e5d/YLS_Series_Card_cms_crd_2x.png?disable=upscale&width=760&format=jpg', '["https://www.ipgphotonics.com/products/lasers/industrial-cw-fiber-lasers/high-power-fiber-lasers","https://cdn.ipgphotonics.com/5b6f3db3-e2af-4331-b634-b0c000f9351e/IPG_YLS-Series_DS_EN_LTR.pdf"]'::jsonb, '2026-08-20', true),
('max-elite-mfsc-500', 'max-photonics', 'max-elite', 'MFSC 500', 'Elite MFSC 500', 'elite-mfsc-500', 'CW / Modulated fiber laser', 500, '500 W', 'Single-module', 'Rack', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥5% typical', '≤ 50 kHz', '≤ 1.1 (@ 10 μm)', 'QBH, QCS', 'Digital I/O (EtherCAT / PROFINET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (power supply), Performance Level D (PL-d)', '2 years standard (extendable to 5 years)', 'Not published on product page', '["Additive manufacturing","Precision processing"]'::jsonb, 'A compact 500 W CW fiber laser engineered for precision 3D printing, combining excellent beam quality, stable output, and reliable industrial performance.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/max/elite/elite-mfsc-500.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfsc_500w-red.jpg', '["https://maxlasers.com/products/elite-mfsc-500","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfsc-1000', 'max-photonics', 'max-elite', 'MFSC 1000', 'Elite MFSC 1000', 'elite-mfsc-1000', 'CW / Modulated fiber laser', 1000, '1000 W', 'Single-module', 'Rack', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥5% typical', '≤ 50 kHz', '≤ 1.2 (@ 14 μm)', 'QBH, QCS', 'Digital I/O (EtherCAT / PROFINET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (power supply), Performance Level D (PL-d)', '2 years standard (extendable to 5 years)', 'Not published on product page', '["Additive manufacturing","Precision processing"]'::jsonb, 'A versatile 1 kW CW fiber laser engineered for precision 3D printing, combining excellent beam quality, stable output, and reliable industrial performance.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/max/elite/elite-mfsc-1000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfsc_1kw-red.jpg', '["https://maxlasers.com/products/elite-mfsc-1000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfsc-2000', 'max-photonics', 'max-elite', 'MFSC 2000', 'Elite MFSC 2000', 'elite-mfsc-2000', 'CW / Modulated fiber laser', 2000, '2000 W', 'Single-module', 'Rack', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '1.0 to 2.0 (@ 50 μm) / 3.0 to 4.0 (@ 100 μm)', 'QBH, QD', 'Digital I/O (EtherCAT / PROFINET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (power supply), Performance Level D (PL-d)', '2 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Welding","Cladding"]'::jsonb, 'A versatile 2 kW CW fiber laser engineered for precision cutting, welding, and cladding, combining excellent beam quality, stable output, and reliable industrial performance.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/max/elite/elite-mfsc-2000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfsc_2kw-red.jpg', '["https://maxlasers.com/products/elite-mfsc-2000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfsc-3000', 'max-photonics', 'max-elite', 'MFSC 3000', 'Elite MFSC 3000', 'elite-mfsc-3000', 'CW / Modulated fiber laser', 3000, '3000 W', 'Single-module', 'Rack', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '1.0 to 2.0 (@ 50 μm) / 3.0 to 4.0 (@ 100 μm)', 'QBH, QD', 'Digital I/O (EtherCAT / PROFINET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (power supply), Performance Level D (PL-d)', '2 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Welding","Cladding"]'::jsonb, 'A versatile 3 kW CW fiber laser engineered for precision cutting, welding, and cladding, combining excellent beam quality, stable output, and reliable industrial performance.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/max/elite/elite-mfsc-3000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfsc_3kw-red.jpg', '["https://maxlasers.com/products/elite-mfsc-3000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfsc-4000', 'max-photonics', 'max-elite', 'MFSC 4000', 'Elite MFSC 4000', 'elite-mfsc-4000', 'CW / Modulated fiber laser', 4000, '4000 W', 'Single-module', 'Rack', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '1.0 to 2.0 (@ 50 μm) / 3.0 to 4.0 (@ 100 μm)', 'QBH, QD', 'Digital I/O (EtherCAT / PROFINET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (power supply), Performance Level D (PL-d)', '2 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Welding","Cladding"]'::jsonb, 'A versatile 4 kW CW fiber laser engineered for precision cutting, welding, and cladding, combining excellent beam quality, stable output, and reliable industrial performance.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/max/elite/elite-mfsc-4000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfsc_4kw-red.jpg', '["https://maxlasers.com/products/elite-mfsc-4000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfsc-6000', 'max-photonics', 'max-elite', 'MFSC 6000', 'Elite MFSC 6000', 'elite-mfsc-6000', 'CW / Modulated fiber laser', 6000, '6000 W', 'Single-module', 'Rack', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '1.0 to 2.0 (@ 50 μm) / 3.0 to 4.0 (@ 100 μm)', 'QBH, QD', 'Digital I/O (EtherCAT / PROFINET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (power supply), Performance Level D (PL-d)', '2 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Welding","Cladding"]'::jsonb, 'A versatile 6 kW CW fiber laser engineered for precision cutting, welding, and cladding, combining excellent beam quality, stable output, and reliable industrial performance.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/max/elite/elite-mfsc-6000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfsc_6kw-red.jpg', '["https://maxlasers.com/products/elite-mfsc-6000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfsc-6000-cabinet', 'max-photonics', 'max-elite', 'MFSC 6000', 'Elite MFSC 6000', 'elite-mfsc-6000-cabinet', 'CW / Modulated fiber laser', 6000, '6000 W', 'Single-module', 'Cabinet', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '3.5 to 4.5 (@ 100 μm) / 4.5 to 6.0 (@ 150 μm) / 8.0 to 10.0 (@ 200 μm)', 'LOE, QD', 'Digital I/O (EtherCAT / PROFINET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, Performance Level D (PL-d)', '2 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Welding","Cladding"]'::jsonb, 'A versatile 6 kW cabinet-mounted CW fiber laser engineered for precision cutting, welding, and cladding, combining stable output, reliable performance, and flexible system integration.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/max/elite/elite-mfsc-6000-cabinet.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfsc_6kw-cabinet-red.jpg', '["https://maxlasers.com/products/elite-mfsc-6000-cabinet","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfsc-12000', 'max-photonics', 'max-elite', 'MFSC 12000', 'Elite MFSC 12000', 'elite-mfsc-12000', 'CW / Modulated fiber laser', 12000, '12000 W', 'Single-module', 'Rack', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '3.5 to 4.5 (@ 100 μm) / 4.5 to 6.0 (@ 150 μm) / 8.0 to 10.0 (@ 200 μm)', 'LOE, QD', 'Digital I/O (EtherCAT / PROFINET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, Performance Level D (PL-d)', '3 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Heavy plate cutting","Welding","Cladding"]'::jsonb, 'A high-power 12 kW CW fiber laser engineered for demanding cutting, welding, and cladding, combining stable output, reliable performance, and seamless industrial integration.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/max/elite/elite-mfsc-12000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfsc_12kw-red.jpg', '["https://maxlasers.com/products/elite-mfsc-12000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfmc-20000', 'max-photonics', 'max-elite', 'MFMC 20000', 'Elite MFMC 20000', 'elite-mfmc-20000', 'CW / Modulated fiber laser', 20000, '20000 W', 'Multi-module', 'Cabinet', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '3.2 to 4.0 (@ 100 μm) / 4.5 to 6.0 (@ 150 μm) / 8.0 to 10.0 (@ 200 μm)', 'LOE', 'Digital I/O (EtherCAT / ProfiNET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (UL compatible) and Performance Level D (PL-d)', '3 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Heavy plate cutting","Welding","Cladding"]'::jsonb, 'High-performance CW fiber lasers. The Elite Series offers superior beam quality, stability, and efficiency for precision and heavy-duty industrial applications.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/max/elite/elite-mfmc-20000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfmc_20kw-red.jpg', '["https://maxlasers.com/products/elite-mfmc-20000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfmc-30000', 'max-photonics', 'max-elite', 'MFMC 30000', 'Elite MFMC 30000', 'elite-mfmc-30000', 'CW / Modulated fiber laser', 30000, '30000 W', 'Multi-module', 'Cabinet', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '3.2 to 4.0 (@ 100 μm) / 4.5 to 6.0 (@ 150 μm) / 8.0 to 10.0 (@ 200 μm)', 'LOE', 'Digital I/O (EtherCAT / ProfiNET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (UL compatible) and Performance Level D (PL-d)', '3 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Heavy plate cutting","Welding","Cladding"]'::jsonb, 'High-performance CW fiber lasers. The Elite Series offers superior beam quality, stability, and efficiency for precision and heavy-duty industrial applications.', true, 'Within at least one published Wavlon machine power range; final engineering validation required.', '/assets/laser-sources/max/elite/elite-mfmc-30000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfmc_30kw-red.jpg', '["https://maxlasers.com/products/elite-mfmc-30000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfmc-40000', 'max-photonics', 'max-elite', 'MFMC 40000', 'Elite MFMC 40000', 'elite-mfmc-40000', 'CW / Modulated fiber laser', 40000, '40000 W', 'Multi-module', 'Cabinet', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '4.0 to 5.5 (@ 100 μm) / 5.5 to 6.5 (@ 150 μm) / 8.0 to 10.0 (@ 200 μm)', 'LOE', 'Digital I/O (EtherCAT / ProfiNET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (UL compatible) and Performance Level D (PL-d)', '3 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Heavy plate cutting","Welding","Cladding"]'::jsonb, 'High-performance CW fiber lasers. The Elite Series offers superior beam quality, stability, and efficiency for precision and heavy-duty industrial applications.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/max/elite/elite-mfmc-40000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfmc_40kw-red.jpg', '["https://maxlasers.com/products/elite-mfmc-40000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfmc-50000', 'max-photonics', 'max-elite', 'MFMC 50000', 'Elite MFMC 50000', 'elite-mfmc-50000', 'CW / Modulated fiber laser', 50000, '50000 W', 'Multi-module', 'Cabinet', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '4.0 to 5.5 (@ 100 μm) / 5.5 to 6.5 (@ 150 μm) / 8.0 to 10.0 (@ 200 μm)', 'LOE', 'Digital I/O (EtherCAT / ProfiNET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA, ETL (UL compatible) and Performance Level D (PL-d)', '3 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Heavy plate cutting","Welding","Cladding"]'::jsonb, 'High-performance CW fiber lasers. The Elite Series offers superior beam quality, stability, and efficiency for precision and heavy-duty industrial applications.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/max/elite/elite-mfmc-50000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfmc_50kw-red.jpg', '["https://maxlasers.com/products/elite-mfmc-50000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfmc-60000', 'max-photonics', 'max-elite', 'MFMC 60000', 'Elite MFMC 60000', 'elite-mfmc-60000', 'CW / Modulated fiber laser', 60000, '60000 W', 'Multi-module', 'Cabinet', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '5.5 to 6.5 (@ 150 μm)', 'LOE', 'Digital I/O (EtherCAT / ProfiNET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA and Performance Level D (PL-d)', '3 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Heavy plate cutting","Welding","Cladding"]'::jsonb, 'High-performance CW fiber lasers. The Elite Series offers superior beam quality, stability, and efficiency for precision and heavy-duty industrial applications.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/max/elite/elite-mfmc-60000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfmc_60kw-red.jpg', '["https://maxlasers.com/products/elite-mfmc-60000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfmc-80000', 'max-photonics', 'max-elite', 'MFMC 80000', 'Elite MFMC 80000', 'elite-mfmc-80000', 'CW / Modulated fiber laser', 80000, '80000 W', 'Multi-module', 'Cabinet', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '5.5 to 6.5 (@ 150 μm)', 'LOE', 'Digital I/O (EtherCAT / ProfiNET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA and Performance Level D (PL-d)', '3 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Heavy plate cutting","Welding","Cladding"]'::jsonb, 'High-performance CW fiber lasers. The Elite Series offers superior beam quality, stability, and efficiency for precision and heavy-duty industrial applications.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/max/elite/elite-mfmc-80000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfmc_80kw-red.jpg', '["https://maxlasers.com/products/elite-mfmc-80000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true),
('max-elite-mfmc-85000', 'max-photonics', 'max-elite', 'MFMC 85000', 'Elite MFMC 85000', 'elite-mfmc-85000', 'CW / Modulated fiber laser', 85000, '85000 W', 'Multi-module', 'Cabinet', 'Random', 'Not published on product page', 'Not published on product page', '±1%', '≥ 5 % (Typ.)', 'Not published on product page', '5.5 to 6.5 (@ 150 μm)', 'LOE', 'Digital I/O (EtherCAT / ProfiNET opt.)', 'Integrated industrial cooling architecture; confirm by configuration', 'CE, FDA and Performance Level D (PL-d)', '3 years standard (extendable to 5 years)', 'Not published on product page', '["Sheet cutting","Heavy plate cutting","Welding","Cladding"]'::jsonb, 'High-performance CW fiber lasers. The Elite Series offers superior beam quality, stability, and efficiency for precision and heavy-duty industrial applications.', false, 'Outside the currently published Wavlon cutting-machine power ranges or intended for a different process; consult engineering.', '/assets/laser-sources/max/elite/elite-mfmc-85000.webp', 'https://maxlasers.fra1.digitaloceanspaces.com/product_renderings/elite/elite-mfmc_85kw-red.jpg', '["https://maxlasers.com/products/elite-mfmc-85000","https://maxlasers.com/products/elite-series"]'::jsonb, '2026-08-20', true)
on conflict (id) do update set
  brand_id = excluded.brand_id,
  series_id = excluded.series_id,
  model = excluded.model,
  display_name = excluded.display_name,
  slug = excluded.slug,
  product_type = excluded.product_type,
  nominal_power_w = excluded.nominal_power_w,
  nominal_power_label = excluded.nominal_power_label,
  module_type = excluded.module_type,
  housing_form = excluded.housing_form,
  polarization = excluded.polarization,
  wavelength = excluded.wavelength,
  power_tunability = excluded.power_tunability,
  power_stability = excluded.power_stability,
  power_redundancy = excluded.power_redundancy,
  modulation_frequency = excluded.modulation_frequency,
  beam_quality = excluded.beam_quality,
  fiber_connectors = excluded.fiber_connectors,
  interface = excluded.interface,
  cooling = excluded.cooling,
  certifications = excluded.certifications,
  warranty = excluded.warranty,
  efficiency = excluded.efficiency,
  applications = excluded.applications,
  description = excluded.description,
  power_range_match = excluded.power_range_match,
  compatibility_note = excluded.compatibility_note,
  primary_image_path = excluded.primary_image_path,
  source_image_url = excluded.source_image_url,
  source_urls = excluded.source_urls,
  source_retrieved_at = excluded.source_retrieved_at,
  published = excluded.published,
  updated_at = now();

comment on table public.laser_source_models is
  'Public read-only laser-source catalog. Static website uses a committed JSON snapshot; Supabase is the maintainable knowledge source.';
